# Generated by Django 5.0.4 on 2024-04-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('key', models.CharField(db_column='key', max_length=10, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('expired', models.DateTimeField(null=True)),
            ],
        ),
    ]
