# Generated by Django 5.0.4 on 2024-04-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('key', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('expired', models.DateTimeField(null=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
