# Generated by Django 5.0.4 on 2024-04-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='key',
            field=models.CharField(db_column='key', max_length=6, primary_key=True, serialize=False),
        ),
    ]
