# Generated by Django 5.0.4 on 2024-04-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_shorturl_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
